### ISSUE TITLE
Paper Review: Related Packages/State of the Field

### ISSUE THREAD

**Issue by joeweaver** [mjacob1002/Eir#10]
There's a list of other packages (which is great!), but there's no explicity comparison between EIR and these. No need to do big analysis or feature-bullet chart.  Just something on the order of a short paragraph that helps me see how EIR fits into the ecosystem.

**Comment by mjacob1002** [comment]
Hi @joeweaver! Sorry for the delay - it's exam season at the moment! I think I addressed the issue by stating how Eir was different from each of the packages when I mentioned them. Let me know if that fixes the issue.

**Comment by mjacob1002** [comment]
Hi @joeweaver, just following up to make sure that the commit to the paper was more in line with what you wanted.

**Comment by joeweaver** [comment]
Hi,

The earlier email flew under my radar somehow I'll be checking out the
changes on Monday.

--Joe

**Comment by joeweaver** [comment]
The updated docs clear up what the tests are doing.

**Comment by joeweaver** [comment]
Removed a comment meant for another issue.  The updated paper places the software in the context of the other packages.
